###BASIC STATISTICS-2###
Problem Statement : Hospital Patient Data Analysis
Context:
A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.
Tasks:
1.	Load the patient dataset and show summary with info().
2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
4.	Use groupby to find total bill amount per department.
5.	Remove duplicate patient records based on PatientID.
6.	Fill missing BillAmount values with the mean bill amount.
7.	Merge the billing dataset with patient dataset on PatientID.
8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).
Expected Outcome:
•	Final cleaned dataset with accurate billing info.
•	All missing values handled, merged dataset across PatientID.
•	Ability to perform further analytics on department-wise revenue or doctor performance.

In [9]:
import pandas as pd

df1 = pd.read_csv("Patient_Data.csv")
df2 = pd.read_csv("Billing_Data.csv")

In [10]:
df1

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [11]:
df1.info()
df2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

###Selecting Relevant Columns###

In [12]:
df1 = df1[['PatientID', 'Department', 'Doctor', 'BillAmount']]

In [13]:
df1

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

####Removing Unnecessary Columns###

In [14]:
df1 = df1.drop(columns=['ReceptionistID', 'CheckInTime'], errors='ignore')

In [15]:
df1

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

####Department-wise Billing Analysis###

In [16]:
dept_bill = df1.groupby('Department')['BillAmount'].sum()
print(dept_bill)

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

###Removing Duplicate Records###

In [17]:
df1 = df1.drop_duplicates(subset='PatientID')

In [18]:
df1

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

In [20]:
####Handling Missing Values####
mean_bill = df1['BillAmount'].mean()
df1['BillAmount'].fillna(mean_bill, inplace=True)

C:\Users\Bhaskar Singh\AppData\Local\Temp\ipykernel_17104\141119808.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['BillAmount'].fillna(mean_bill, inplace=True)
C:\Users\Bhaskar Singh\AppData\Local\Temp\ipykernel_17104\141119808.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['BillAmount'].fillna(mean_bill, inplace=True)

In [21]:
df1

   PatientID   Department     Doctor   BillAmount
0        101   Cardiology  Dr. Smith  5000.000000
1        102    Neurology   Dr. John  6233.333333
2        103  Orthopedics    Dr. Lee  7500.000000
3        104   Cardiology  Dr. Smith  6200.000000
4        105  Dermatology   Dr. Rose  6233.333333

####Merging Datasets####

In [22]:
new_df = pd.merge(df1, df2, on='PatientID', how='inner')

In [23]:
new_df

,PatientID,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Neurology,Dr. John,6233.333333,1500,3500
2,103,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Dermatology,Dr. Rose,6233.333333,1000,4000

####Adding New Patient Data###

In [24]:
new_patients = pd.DataFrame({
    'PatientID': [101, 102],
    'Department': ['Cardiology', 'Neurology'],
    'Doctor': ['Dr A', 'Dr B'],
    'BillAmount': [5000, 7000]
})

new_df = pd.concat([new_df, new_patients], axis=0)

In [25]:
new_df

,PatientID,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Cardiology,Dr. Smith,5000.000000,2000.0,3000.0
1,102,Neurology,Dr. John,6233.333333,1500.0,3500.0
2,103,Orthopedics,Dr. Lee,7500.000000,2500.0,5000.0
3,104,Cardiology,Dr. Smith,6200.000000,3000.0,3200.0
4,105,Dermatology,Dr. Rose,6233.333333,1000.0,4000.0
0,101,Cardiology,Dr A,5000.000000,NaN,NaN
1,102,Neurology,Dr B,7000.000000,NaN,NaN

In [26]:
####Adding New Billing Columns ####

In [28]:
new_columns = pd.DataFrame({
    'InsuranceCovered': [True] * len(new_df),
    'FinalAmount': new_df['BillAmount'] * 0.9
})

new_df = pd.concat([new_df, new_columns], axis=1)

In [30]:
new_df.head()

,PatientID,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount,InsuranceCovered,FinalAmount
0,101,Cardiology,Dr. Smith,5000.000000,2000.0,3000.0,True,4500.0
1,102,Neurology,Dr. John,6233.333333,1500.0,3500.0,True,5610.0
2,103,Orthopedics,Dr. Lee,7500.000000,2500.0,5000.0,True,6750.0
3,104,Cardiology,Dr. Smith,6200.000000,3000.0,3200.0,True,5580.0
4,105,Dermatology,Dr. Rose,6233.333333,1000.0,4000.0,True,5610.0

###Conclusion####

In this assignment, the hospital dataset was successfully cleaned and processed. Relevant columns were selected, unnecessary data was removed, and duplicate records were handled. Missing values were filled using mean imputation.

The datasets were merged properly using PatientID, and additional data was added to enhance analysis. The final dataset is well-structured and can be used for further insights like department revenue, billing trends, and doctor performance.